apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-application-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
